name: luminova
description: "admin panel flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  animations: ^2.0.11
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  convert: ^3.1.1
  equatable: ^2.0.5
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.14.1
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  open_file: ^3.5.10
  permission_handler: ^11.3.1
  pull_to_refresh_flutter3: ^2.0.2
  shared_preferences: ^2.3.2
  syncfusion_flutter_charts: ^27.2.2

flutter_icons:
  android: true
  ios: true
  linux: true
  image_path: "assets/images/luminova.png"
  min_sdk_android: 30 # android min sdk min:16, default 21
  adaptive_icon_background: "#2A3132" # hanya untuk Android 8.0 ke atas
  adaptive_icon_foreground: "assets/images/luminova.png" # hanya untuk Android 8.0 ke atas
  remove_alpha_ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12

flutter:
  assets:
    - assets/images/
    - assets/favicon/
    - .env
  uses-material-design: true
